### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Google-Autofuzz** [sleuthkit/sleuthkit#1006]
Hello sleuthkit team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
sleuthkit (tested with revision * develop a8364cdf8cd2487a262a91f7ae073c9d925f81f3).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

=================================================================
==17==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 536 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53a6ce in hfs_make_specialbase /fuzzing/sleuthkit/tsk/fs/hfs.c:1829:17
    #3 0x530a8b in hfs_make_extents /fuzzing/sleuthkit/tsk/fs/hfs.c:1947:9
    #4 0x51f9d5 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2542:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #7 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #8 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #9 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #10 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #11 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #12 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 536 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53a6ce in hfs_make_specialbase /fuzzing/sleuthkit/tsk/fs/hfs.c:1829:17
    #3 0x531f27 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1868:9
    #4 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #7 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #8 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x514ab3 in tsk_fs_meta_alloc /fuzzing/sleuthkit/tsk/fs/fs_inode.c:42:29
    #3 0x51f901 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2517:27
    #4 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #5 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #6 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #7 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x514ab3 in tsk_fs_meta_alloc /fuzzing/sleuthkit/tsk/fs/fs_inode.c:42:29
    #3 0x51f901 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2517:27
    #4 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #5 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #6 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #7 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #8 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #9 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #10 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #11 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x514aec in tsk_fs_meta_alloc /fuzzing/sleuthkit/tsk/fs/fs_inode.c:48:37
    #3 0x51f901 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2517:27
    #4 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #5 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #6 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #7 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x514aec in tsk_fs_meta_alloc /fuzzing/sleuthkit/tsk/fs/fs_inode.c:48:37
    #3 0x51f901 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2517:27
    #4 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #5 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #6 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #7 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #8 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #9 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #10 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #11 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x63bde7 in tsk_fs_attr_alloc /fuzzing/sleuthkit/tsk/fs/fs_attr.c:85:44
    #3 0x63fc90 in tsk_fs_attrlist_getnew /fuzzing/sleuthkit/tsk/fs/fs_attrlist.c:163:32
    #4 0x530eac in hfs_make_extents /fuzzing/sleuthkit/tsk/fs/hfs.c:1968:13
    #5 0x51f9d5 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2542:16
    #6 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #7 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #8 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #9 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #10 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #11 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #12 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #13 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x63bde7 in tsk_fs_attr_alloc /fuzzing/sleuthkit/tsk/fs/fs_attr.c:85:44
    #3 0x63fc90 in tsk_fs_attrlist_getnew /fuzzing/sleuthkit/tsk/fs/fs_attrlist.c:163:32
    #4 0x532369 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1890:13
    #5 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #6 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #7 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #8 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #9 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53acc1 in hfs_extents_to_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:404:24
    #3 0x5322f1 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1883:17
    #4 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #7 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #8 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53acc1 in hfs_extents_to_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:404:24
    #3 0x530e4c in hfs_make_extents /fuzzing/sleuthkit/tsk/fs/hfs.c:1961:17
    #4 0x51f9d5 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2542:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #7 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #8 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #9 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #10 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #11 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #12 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x5135f2 in tsk_fs_file_alloc /fuzzing/sleuthkit/tsk/fs/fs_file.c:31:31
    #3 0x51388b in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:113:24
    #4 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #5 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #6 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #7 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #8 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #9 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #10 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x5135f2 in tsk_fs_file_alloc /fuzzing/sleuthkit/tsk/fs/fs_file.c:31:31
    #3 0x51388b in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:113:24
    #4 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #5 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #6 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53a78c in hfs_make_specialbase /fuzzing/sleuthkit/tsk/fs/hfs.c:1841:31
    #3 0x531f27 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1868:9
    #4 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #7 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #8 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4ccf98 in __interceptor_malloc (/fuzzing/sleuthkit/tools/fstools/fls+0x4ccf98)
    #1 0x5bb23e in tsk_malloc /fuzzing/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x53a78c in hfs_make_specialbase /fuzzing/sleuthkit/tsk/fs/hfs.c:1841:31
    #3 0x530a8b in hfs_make_extents /fuzzing/sleuthkit/tsk/fs/hfs.c:1947:9
    #4 0x51f9d5 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2542:16
    #5 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #6 0x53b12d in hfs_ext_find_extent_record_attr /fuzzing/sleuthkit/tsk/fs/hfs.c:468:17
    #7 0x532cc9 in hfs_make_catalog /fuzzing/sleuthkit/tsk/fs/hfs.c:1909:9
    #8 0x51fa96 in hfs_inode_lookup /fuzzing/sleuthkit/tsk/fs/hfs.c:2545:16
    #9 0x5138bc in tsk_fs_file_open_meta /fuzzing/sleuthkit/tsk/fs/fs_file.c:128:9
    #10 0x521871 in hfs_open /fuzzing/sleuthkit/tsk/fs/hfs.c:6461:13
    #11 0x508e89 in main /fuzzing/sleuthkit/tools/fstools/fls.cpp:267:19
    #12 0x7f12eb7fe2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: 2360 byte(s) leaked in 15 allocation(s).

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
69014592

**Comment by APriestman** [comment]
I don't see any attached files for this issue?

**Comment by Google-Autofuzz** [comment]
Sorry about that, and thanks for looking at the issue.  Here are the files associated with this issue.
[artifacts_69014592.zip](https://github.com/sleuthkit/sleuthkit/files/1536513/artifacts_69014592.zip)
