### ISSUE TITLE
Compile  usnjls on Windows

### ISSUE THREAD

**Issue by ahuri** [sleuthkit/sleuthkit#1060]
I need to parse $USN file, and I need usnjls for that. Since this tool is compiled only on the Linux version, I tried to compile it with VS on Windows machine.

While trying to do so, I get an error message: "Cannot open include file: 'libewf.h': No such file or directory".
This error is referred to the line: `#include <libewf.h>` in 'ewf.h'

Can someone help me to figure this out please? It's very urgent.

Thanks in advance!

**Comment by rcordovano** [comment]
Have you downloaded and built the Visual Studio project for VS 2015 from https://github.com/sleuthkit/libewf_64bit?

**Comment by rcordovano** [comment]
@ahuri, please allow me to also refer you to the guide to building TSK for Widows at https://github.com/sleuthkit/sleuthkit/blob/develop/win32/BUILDING.txt.

**Comment by ahuri** [comment]
Thank you for your help.
Finally, after a lot of work, I don't get compilation errors, but a lot (40) linker errors.
All LNK2001 errors. which divide to:
1) unresolved external symbol _tsk_fs_usnjls
2) unresolved external symbol _libvhdi_* (11 errors)
3) unresolved external symbol _libewf_* (13 errors)
4) unresolved external symbol _libvmdk_* (11 errors)
5) unresolved external symbol _inflate* (3 errors)
6) unresolved external symbol _WinMain@16

All errors are referred to 'usnjls' project. After hard work I succeed to build 'libewf_dll' project, and 'libvhdi' + 'libvmdk' were compiled without any problem.

Any solution for that situation please?

**Comment by rcordovano** [comment]
@ahuri, can I assume you successfully set the LIBEWF_HOME, LIBVMDK_HOME, and LIBVHDI_HOME environment variables? TSK uses these to find the libewf, libvmdk, and libvhdi DLLs.

I don't have a usjls project in the TSK solution as I look at it in Microsoft Visual Studio. Is this project from somewhere else besides https://github.com/sleuthkit/sleuthkit?

**Comment by ahuri** [comment]
Here: https://github.com/sleuthkit/sleuthkit/tree/develop/tools/fstools
Like I mentioned, this tool is not compiled for the Windows version of TSK.

**Comment by rcordovano** [comment]
@ahuri, thanks, I missed that detail.  So did you create a Visual Studio project, or are you building using a different IDE / compiler? If you are using Visual Studio, you need to set the additional library properties for the linker for the project:

![image](https://user-images.githubusercontent.com/1713605/34414195-e73ea5f4-ebb5-11e7-9783-c8431e538d2a.png)

**Comment by ahuri** [comment]
Yes. I've done it already.
Maybe need to specify the lib files, but I have no lib files under "release" directory in libvhdi or libvmdk...

**Comment by rcordovano** [comment]
Are you doing a 32-bit or 64-bit build? I normally do 64-bit builds and my lib files are in ~\libvhdi_64bit\msvscpp\x64\Release and  ~\libvmdk_64bit\libvmdk\msvscpp\x64\Release. The 32-bit libs go in ~\libvhdi_64bit\msvscpp\Release and ~\libvmdk_64bit\libvmdk\msvscpp\Release.

**Comment by ahuri** [comment]
I will check the issue again and let you know. Thanks!

**Comment by ahuri** [comment]
In usnjls\x64\Release there are no .lib files at all.
Only .log files, and usnjls.obj, vc140.pdb.

**Comment by ahuri** [comment]
OK. I tried to add the "libvhdi.lib, libvmdk.lib..." files to Additional Dependencies in Linker>Input.
That solved the most of the linker issues.
Then I changed Linker>System>SubSystem to "Console" and that solved the "WinMain" issue.
But one last linker problem persists - "unresolved external symbol tsk_fs_usnjls" (refers to usnjls.obj).

Any idea?

**Comment by rcordovano** [comment]
@ahuri, I am glad I was able to help, even if only a little bit. Shall we close this issue?

**Comment by ahuri** [comment]
Yes.
Thanks.
