### ISSUE TITLE
AS_ECHO in JNI testing

### ISSUE THREAD

**Issue by robjoyce** [sleuthkit/sleuthkit#108]
On OS X 10.6 and 10.7, which have autoconf 2.61, the generated ./configure has an undefined AS_ECHO macro.  This comes from m4/ax_jni_include_dir.m4.  Changing the two occurrences of AS_ECHO to AC_MSG_NOTICE fixes the problem.  (AC_MSG_NOTICE seems to be preferred for user messages, anyway, because it respects the --silent flag.)

(I should probably update my autoconf, but I figured I should tell you because 2.61 is a common default on OS X.)

**Comment by uckelman-sf** [comment]
@simsong This was fixed (long ago) and should be closed.
