### ISSUE TITLE
Heap read overflow in raw_read()

### ISSUE THREAD

**Issue by Google-Autofuzz** [sleuthkit/sleuthkit#1112]
Hello Sleuthkit team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
sleuthkit (tested with revision 2a9a69bd414bdc33762c8766417db019c77eccfb).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

==34==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000efb8 at pc 0x00000050c633 bp 0x7fffa1b156e0 sp 0x7fffa1b156d8
READ of size 8 at 0x60200000efb8 thread T0
    #0 0x50c632 in raw_read /fuzzing/sleuthkit/tsk/img/raw.c:284:25
[sleuthkit-2018012902.zip](https://github.com/sleuthkit/sleuthkit/files/1671983/sleuthkit-2018012902.zip)

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team

**Comment by esaunders** [comment]
To get the provided Dockerfile to build I had to upgrade the version of LLVM (from 3.9 to 5.0).
When the container built successfully I was unable to reproduce the heap read overflow in raw_read(). I suspect the issue was fixed by https://github.com/sleuthkit/sleuthkit/commit/0fb4584b4553d3237313e15363f6d4fa0241f27c
