### ISSUE TITLE
Missing source signatures for v4.5.0

### ISSUE THREAD

**Issue by svetlemodry** [sleuthkit/sleuthkit#1133]
On the latest release, the .asc signature files are missing. Any chance to add them?
See [v4.5.0](https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.5.0) vs [v4.4.2](https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.4.2)
Thanks!

**Comment by bcarrier** [comment]
Just added them (as I'm building 4.6.0). . Sorry about that.
