### ISSUE TITLE
LVM Decoding

### ISSUE THREAD

**Issue by crssantos** [sleuthkit/sleuthkit#1148]
I realized that sleuthkit doesn´t recognize Linux Logical Volume Manager (LVM) partitions. 

How can I solve this problem?

Thanks in advance.

**Comment by gilsonm112** [comment]
Linux Volume Manager and I have stopped using Sleuthkit because it does not support them, it would be nice to include this support

**Comment by lfcnassif** [comment]
Up

**Comment by igheid** [comment]
Up
