### ISSUE TITLE
%lld error in db_sqlite.cpp

### ISSUE THREAD

**Issue by simsong** [sleuthkit/sleuthkit#119]
I've been getting this error when compiling on Ubuntu 12.10 and FC17:

```
db_sqlite.cpp:1090:81: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘int64_t {aka long int}’ [-Wformat]
```

**Comment by uckelman-sf** [comment]
I don't see this warning currently on Fedora 39 or in the build runners. Seems to have been fixed.
