### ISSUE TITLE
potential relicensed (L)GPL code in ext2fs.c test_root

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1251]
From https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/ext2fs.c#L67

```
/** \internal
    test_root - tests to see if a is power of b
    Adapted from E2fsprogs sparse.c
    Super blocks are only in block groups that are powers of 3,5, and 7
    @param a the number being investigated
    @param b the root
    @return 1 if a is a power of b, otherwise 0
*/
static uint8_t
test_root(uint32_t a, uint32_t b)
{
    if (a == 0)
        return 1;
    while (1) {
        if (a == 1)
            return 1;
        if (a % b)
            return 0;
        a = a / b;
    }
}
```

Looking at https://git.busybox.net/busybox/plain/e2fsprogs/ext2fs/sparse.c?h=1_3_stable

```
static int test_root(int a, int b)
{
	if (a == 0)
		return 1;
	while (1) {
		if (a == 1)
			return 1;
		if (a % b)
			return 0;
		a = a / b;
	}
}
```

Docstring says code "adapted" from E2fsprogs sparse.c, looks directly copied.
How is this code "adapted", it looks exactly like the original?

**Comment by joachimmetz** [comment]
@uckelman-sf this would still imply the code was re-licensed not adopted

**Comment by bcarrier** [comment]
Looks like this came in via the Ext4 contribution:

https://github.com/sleuthkit/sleuthkit/commit/861dc179aa6e2a61f675806a3a552f0cc5bee34c

Seems like we can easily just divide by the log of the power to figure this out and not have to bring in any LGPL.

**Comment by joachimmetz** [comment]
@bcarrier please check the source for more of these issue, this is the third time that I've spotted code that has been re-licensed in this code base:

* https://github.com/sleuthkit/sleuthkit/issues/1146
* https://github.com/sleuthkit/sleuthkit/issues/933

**Comment by bcarrier** [comment]
Will do. All of these have been contributed code. Are there fancy tools to help to this or have you just noticed the  "adapted from" comments?

**Comment by joachimmetz** [comment]
I was troubleshooting an ext related issue and noticed that the e2fsprogs and tsk code looked the same. I guess that there are tools for this. Another way is to verify contribute code that states it was adopted.

**Comment by hoyt-harness** [comment]
Here's one option, but it's not cheap: https://www.blackducksoftware.com/solutions/open-source-license-compliance

**Comment by crawfxrd** [comment]
[FOSSology](https://www.fossology.org/) ([GitHub](https://github.com/fossology/fossology))

> FOSSology is a open source license compliance software system and toolkit. As a toolkit you can run license, copyright and export control scans from the command line. As a system, a database and web ui are provided to give you a compliance workflow. License, copyright and export scanners are tools available to help with your compliance activities.
