### ISSUE TITLE
Where is tsk_analyzeimg?

### ISSUE THREAD

**Issue by nathan-bowman** [sleuthkit/sleuthkit#1432]
Ubuntu Server 18.04

I have tried installing sleuthkit from both source and `apt install -y sleuthkit`, and I don't see tsk_analyzemg being available.

I see this directory `sleuthkit/framework/tools/tsk_analyzeimg/` and some documentation about it, here: https://www.sleuthkit.org/sleuthkit/framework/man/tsk_analyzeimg.html

Is this a Windows only function?

**Comment by bcarrier** [comment]
It's part of the framework, which is not supported or maintained anymore.  We use the Autopsy framework for our stuff now.
