### ISSUE TITLE
Can't install on Catalina

### ISSUE THREAD

**Issue by fredOnGitHub** [sleuthkit/sleuthkit#1719]
Hello,

$ ./configure 
doesn't work, I get

zsh: no such file or directory: ./configure

brew install autoconf 
and
brew install automake

give the same, even if I do chmod 755 configure.ac

even if 
~/Downloads/sleuthkit-develop % ./configure.ac        
./configure.ac: line 1: dnl: command not found
./configure.ac: line 2: dnl: command not found
./configure.ac: line 5: syntax error near unexpected token `2.59'
./configure.ac: line 5: `AC_PREREQ(2.59)'

Thanks for you help

**Comment by bcarrier** [comment]
If you cloned the repo, you need to run "./bootstrap" to get the configure file in place. Unless you want to change the code, you should just download a released tar ball from:

https://github.com/sleuthkit/sleuthkit/releases
