### ISSUE TITLE
APFS branch removed?

### ISSUE THREAD

**Issue by DannyKielman** [sleuthkit/sleuthkit#1735]
I was trying to setup TSK with APFS support but suddenly the branch is removed?

Who did this? 😡

Edit: I see it's in the dev branch now

**Comment by DannyKielman** [comment]
Actually there aren't any stable commits with APFS support. Why have these branches been merged?

**Comment by rcordovano** [comment]
The apfs branch was a feature development branch created for the use of developers here at Basis Technology, carrying forward community contributions. We are preparing for TSK release 4.8.0, which will have the first version of APFS support, so the apfs branch was merged into the release-4.8.0 branch and then the apfs branch was deleted. We are currently doing pre-release testing on the release-4.8.0 branch. 

During the run up to a release, the release branch is regularly merged into the develop branch. The develop branch will, however, begin to diverge from the current release branch at the point that a commit is made into it for a release farther into the future. 

There is only one branch that can be considered to be the current stable branch - the master branch. All other branches are development branches, subject to significant changes and, excepting the develop branch, also subject to deletion at any time. Anybody in the community is always welcome to try out any branch they wish, but should proceed with the understanding that there are no guarantees for stability for any branch other than master or for the continued existence of any branches other than develop and master. 

Pull requests for community contributions should target the develop branch. Decisions about the acceptance of community contributions are made by @bcarrier.

@DannyKielman, you are correct that there is as of yet no stable branch with APFS support. I am truly sorry for any inconvenience you have experienced, and I hope my explanation of our use of git branching during the development process has helped.  If you want to stay on the cutting edge with respect to APFS support in TSK, I think your best bet is to switch to the release-4.8.0 branch. The TSK 4.8.0 release is currently scheduled for early January, 2020. Please note that our APFS support will not be considered to be complete in the TSK 4.8.0 release. It should be viewed as an initial capability.

**Comment by DannyKielman** [comment]
Thank you for your extensive explanation. I am currently doing a research project into APFS and am comparing the outputs of several different tools. I will look forward to the TSK 4.8.0. release.
