### ISSUE TITLE
Error getting java binding dependencies because of insecure URLs.

### ISSUE THREAD

**Issue by tcmal** [sleuthkit/sleuthkit#1793]
Line 108 of `build.xml` references `http://repo2.maven.org`, however all requests to this host now need https, meaning downloading ivy will fail. [Support article given](https://support.sonatype.com/hc/en-us/articles/360041287334).

Even after changing this, ivy will still fail to download dependencies as it also uses an http only link. I'm not sure how to change this though.

**Comment by HappyLer** [comment]
You can change `bindings/java/ivysettings.xml` to the following: 
```
<ivysettings>
  <settings defaultResolver="default"/>
  <resolvers>
    <chain name="default">
    <ibiblio name="central" m2compatible="true" root="https://repo1.maven.org/maven2/"/>
    <ibiblio name="ibiblio" m2compatible="true"/>
    </chain>
  </resolvers>
</ivysettings>
```
This should force ivy to get the dependencies via https.

**Comment by esaunders** [comment]
This has been fixed here https://github.com/sleuthkit/sleuthkit/pull/1788
