### ISSUE TITLE
Update c_LibExifModule?

### ISSUE THREAD

**Issue by mika** [sleuthkit/sleuthkit#1807]
In Debian we've an open bug report [(#795052)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795052) regarding usage of embedded libexif.

Looking into `framework/modules/c_LibExifModule`, its `NEWS` file refers to a no-longer existing URL/project: https://github.com/sleuthkit/c_LibExifModule/issues which ends in a 404.

Also there are quite some (security related) bugfixes in libexif (currently being at 0.6.21), while `framework/modules/c_LibExifModule` is still on 0.6.20. Even the latest stable release 0.6.21 is very old and there are *many* changes pending in libexif git master (see https://github.com/libexif/libexif/commits/master), waiting to see a new release (tracked in https://github.com/libexif/libexif/issues/12).

Maybe it would make sense to update the `framework/modules/c_LibExifModule` to a more recent version?
And maybe we could clarify the question especially for Debian: does the embedded libexif actually matter for non-Windows builds?

Thanks!

**Comment by bcarrier** [comment]
Closing this since the framework has been removed from the codebase.

**Comment by mika** [comment]
Thank you!
