### ISSUE TITLE
BSD license missing in licenses directory?

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1839]
The following file has a BSD 3-clause license:
https://github.com/sleuthkit/sleuthkit/blob/9e4bc4b5c0d34dcb266191558337be1e199af3da/tsk/fs/lzvn.c

but that license is not included in:
https://github.com/sleuthkit/sleuthkit/tree/9e4bc4b5c0d34dcb266191558337be1e199af3da/licenses

**Comment by joachimmetz** [comment]
Or in https://github.com/sleuthkit/sleuthkit/blob/develop/debian/copyright for that matter

**Comment by bcarrier** [comment]
Thanks! I added the BSD license and also included the MIT for the GUID code that we use. 

But, I'm unsure what to do about the Debian file.  The references I saw online say it declares the primary license. Do you know where to include the BSD reference?

**Comment by joachimmetz** [comment]
Yes add an additional Files section to your copyright file as indicated in the example of https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#copyright

**Comment by joachimmetz** [comment]
More license qualms https://github.com/sleuthkit/sleuthkit/issues/1895

**Comment by joachimmetz** [comment]
And https://github.com/sleuthkit/sleuthkit/issues/1904

**Comment by joachimmetz** [comment]
https://github.com/sleuthkit/sleuthkit/issues/2028

**Comment by joachimmetz** [comment]
Looks like this issue was addressed in https://github.com/sleuthkit/sleuthkit/commit/07c1cf9b74bad6f2da18d7e2bf0ff801ff09c983 and likely can be closed
