### ISSUE TITLE
-k support in tools for APFS

### ISSUE THREAD

**Issue by mbhatt1** [sleuthkit/sleuthkit#1843]
Hello, 

Was wondering why the -k support for APFS was removed? I could re-add it? Or not!

Please advise. 

Thanks, 
Alex

**Comment by APriestman** [comment]
We could not get the crypto library working with our automated testing.

**Comment by mbhatt1** [comment]
Hmm... How do I replicate the issue?

**Comment by APriestman** [comment]
If you look at any of the open PRs, you can see a section where there are three checks. For example, on this PR https://github.com/sleuthkit/sleuthkit/pull/1837 you can see that codacy, appveyor and travis passed. So if you want to make a PR to restore the openssl library, it'll need to pass the appveyor and travis checks.

**Comment by simsong** [comment]
Do you have a test disk?

**Comment by APriestman** [comment]
This PR seems to have enabled the APFS encryption on linux: https://github.com/sleuthkit/sleuthkit/pull/2968
This renaming of HAVE_LIBOPENSSL broke APFS encryption for the Visual Studio build which worked until this point.

Anyway just tried building develop on Ubuntu and it kind of works? I get a core dump after listing the files though.
<tt>~/work/tsk/sleuthkit$ tools/fstools/fls -B 2070 -k password ../../images/apfs_one_encrypted_vol_password.dd
r/r 21: enc.txt
r/r 20: .DS_Store
r/r 22: animal-animal-photography-blurred-background-2071873.jpg
d/d 16: .Trashes
d/d 18: .fseventsd
free(): invalid pointer
Aborted (core dumped)</tt>

**Comment by simsong** [comment]
Can you share the disk image?

**Comment by APriestman** [comment]
https://drive.google.com/file/d/17Nt7Y5eOXPQx3d3WcGs4AXqdbE-EyOb0/view?usp=sharing

**Comment by APriestman** [comment]
Ok this isn't the most well-tested fix I've done (I've only got my one small test image that doesn't have any deleted files) but it seems to be working.
<pre>
C:\Projects\sleuthkit\win32\x64\Release>tsk_recover -B 2070 -k password -f apfs -a "r:\work\images\Encrypted Images\apfs_one_encrypted_vol_password.dd" out
Files Recovered: 6

C:\Projects\sleuthkit\win32\x64\Release>dir out
 Volume in drive C is OS
 Volume Serial Number is F8D4-2226

 Directory of C:\Basis\Projects\sleuthkit\win32\x64\Release\out

11/29/2024  04:49 PM    <DIR>          .
11/29/2024  04:49 PM    <DIR>          ..
11/29/2024  04:49 PM             6,148 .DS_Store
11/29/2024  04:49 PM    <DIR>          .fseventsd
11/29/2024  04:49 PM            76,094 animal-animal-photography-blurred-background-2071873.jpg
11/29/2024  04:49 PM                26 enc.txt
               3 File(s)         82,268 bytes
               3 Dir(s)  46,604,083,200 bytes free
</pre>

https://github.com/sleuthkit/sleuthkit/pull/3116

**Comment by simsong** [comment]
Great. This is a big image, so I'll be re-encoding it as E01 and then adding it to https://github.com/sleuthkit/sleuthkit_test_data when I'm back on a high-speed network.
