### ISSUE TITLE
Missing License Text in Some Header Files

### ISSUE THREAD

**Issue by davidbeveridge** [sleuthkit/sleuthkit#1904]
It appears that some headers are lacking explicit license declarations, this was found during evaluation for potential use of `fls.exe`

Some examples for our view:
tsk/tsk_tools_i.h
tsk/hashdb/tsk_hashdb.h
tsk/pool/tsk_pool.h

This as this is likely to make OSS compliance lawyers nervous.

**Comment by bcarrier** [comment]
There are still some to do some research on.  Namely 'decmpfs.c'.  But, some are fixed.

**Comment by bcarrier** [comment]
I'm closing this story because I think all of the files have a license/copyright on them at this point.
