### ISSUE TITLE
Compile Error: Unnamed class used in typedef (MSVC C5208 error)

### ISSUE THREAD

**Issue by SammyB428** [sleuthkit/sleuthkit#1934]
Using Visual Studio 16.6,  tsk_apfs.hpp and apfs.cpp fail to compile.

tsk_apfs.hpp line 982 reads
using crypto_info_t = struct {

This is basically typedef'ing an unnamed struct to crypto_info_t
Instead just name the struct

struct crypto_info_t  {

apfs.cpp line 593 is
using key_type = struct {
should just be
struct key_type {

**Comment by bcarrier** [comment]
Closing this since it looks like it was also addressed in a PR #1935. Thanks.
