### ISSUE TITLE
A logic error when validating a data run (NTFS)

### ISSUE THREAD

**Issue by msuhanov** [sleuthkit/sleuthkit#1972]
https://github.com/sleuthkit/sleuthkit/blob/c5f90e4680868d4efd82743a45e8497ea52f320f/tsk/fs/ntfs.c#L661

Reads now:
`if (NTFS_RUNL_LENSZ(run) > 8) {`

Should be:
`if (NTFS_RUNL_OFFSZ(run) > 8) {`

**Comment by msuhanov** [comment]
Related:
https://github.com/sleuthkit/sleuthkit/commit/f279cbffbdb462a85438d648d5d18790c0b2b3a0
https://github.com/sleuthkit/sleuthkit/issues/1188

**Comment by bcarrier** [comment]
I think you're right. I'm confirming.

**Comment by bcarrier** [comment]
Thanks. PR #2020 was created for this.
