### ISSUE TITLE
fls with ext4: multiple errors on inode with inline data

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1979]
Tested with Sleuthkit 4.7 

Test file generated by https://github.com/dfirlabs/ext-specimens 

```
fls -r ext4_with_inline_data.raw
d/d 11:	lost+found
r/r 12:	emptyfile
d/d 13:	testdir1
r/r 14:	file_hardlink1
l/l 16:	file_symboliclink1
l/l 17:	directory_symboliclink1
r/r 18:	nfc_téstfilè
r/r 19:	nfd_téstfilè
r/r 20:	nfd_¾
r/r 21:	nfkd_3⁄4
V/V 1025:	$OrphanFiles

echo $?
0
```

Expected is that fls returns an error code since it cannot read the contents of testdir1

```
fls ext4_with_inline_data.raw 13
Error extracting file from image (ext2fs_dir_open_meta: Error reading directory contents: 13
)

echo $?
1
```

Expected is that fls handles the inline stored directory entries

**Comment by garfi303** [comment]
This would seem like a significant issue, as one could create a simple anti-forensics tool that will simply add inline data to disk images and break TSK's ability to analyze them. @bcarrier , are there any plans to address this?

**Comment by simsong** [comment]
This seems an important issue. @bcarrier, are there plans to address it?

**Comment by joachimmetz** [comment]
Draft PR https://github.com/sleuthkit/sleuthkit/pull/2040
