### ISSUE TITLE
Sleuthkit provides seriously out dated version of third party dependencies 

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#1991]
What is going on with the maintenance of the Sleuthkit project? Things are seriously out of date and broken all over the place

https://github.com/sleuthkit/libvhdi_64bit
https://github.com/sleuthkit/libvmdk_64bit

Provide 4 year old versions, update these

https://github.com/sleuthkit/libewf_64bit

An even older, use latest version in https://github.com/libyal/libewf-legacy instead

**Comment by bcarrier** [comment]
Thanks @joachimmetz. VMDK and VHDI were already on our list for this quarter to update. We've been getting reports of issues with VMDK files and are hoping the upgrade helps.  We're also looking at making Nuget packages for them to make it easier for developers to build TSK and Autopsy.

I didn't realize the libewf-legacy repo existed.  I thought we were on the last 'stable' version.  We'll update that one too.

**Comment by joachimmetz** [comment]
> We've been getting reports of issues with VMDK files and are hoping the upgrade helps. 

Please report these upstream if the issues persist.

> We're also looking at making Nuget packages for them to make it easier for developers to build TSK and Autopsy.

Please only do so if you're serious about keeping them up to date. Having older versions easily install-able IMHO is not a good alternative.

**Comment by bcarrier** [comment]
PR #2011 changes TSK to now use nuget. Thanks for making those @joachimmetz.
