### ISSUE TITLE
Compilation issue with fiwalk on 4.10.1

### ISSUE THREAD

**Issue by kwizart** [sleuthkit/sleuthkit#2066]
When building sleuthkit on Fedora Rawhide (f34), I'm experiencing the following error:
(note that the f33 build has succeeded).

make[3]: Leaving directory '/builddir/build/BUILD/sleuthkit-sleuthkit-4.10.1/tools/fiwalk/src'
/usr/bin/ld: sha2.o (symbol from plugin): undefined reference to symbol 'SHA384_Final@@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libcrypto.so.1.1: error adding symbols: DSO missing from command line

For some reason the linker believe libcrypto is needed but the sha2.c should implement the needed functions instead.
I wonder if sha2.c functions should be turned static or symbol-visibility...

**Comment by simsong** [comment]
Has this been resolved?

**Comment by kwizart** [comment]
Indeed, fixed by a later build.
Closing
