### ISSUE TITLE
sleuthkit-4.10.1.jar released in sleuthkit-java_4.10.1-1_amd64.deb was compiled with java 11 instead of 8

### ISSUE THREAD

**Issue by mfrade** [sleuthkit/sleuthkit#2080]
I have downloaded sleuthkit-java_4.10.1-1_amd64.deb and installed it:
```
wget https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.10.1/sleuthkit-java_4.10.1-1_amd64.deb
sudo apt install ./sleuthkit-java_4.10.1-1_amd64.deb
```

After unzipping the file
`https://github.com/sleuthkit/autopsy/releases/download/autopsy-4.17.0/autopsy-4.17.0.zip` and run the script  `unix_setup.sh` I tried to run autopsy 4.17 on ubuntu 18.04 and got the following error:
```
org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: 
/home/user/autopsy-4.17.0/autopsy/modules/org-sleuthkit-autopsy-core.jar: 
java.lang.UnsupportedClassVersionError: org/sleuthkit/datamodel/SleuthkitJNI 
has been compiled by a more recent version of the Java Runtime (class file version 55.0),
this version of the Java Runtime only recognizes class file versions up to 52.0
```

Then I checked the java version used to compile the file `sleuthkit-4.10.1.jar`:
```
$ unzip -p autopsy-4.17.0/autopsy/modules/ext/sleuthkit-4.10.1.jar META-INF/MANIFEST.MF
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.5
Created-By: 11.0.9+12-LTS (BellSoft)
```

It seems that `sleuthkit-4.10.1.jar` was compiled with java 11 instead of 8

**Comment by mfrade** [comment]
I just want to add that I was able to run autopsy 4.17 on Ubuntu 18.04 after compiling `sleuthkit-4.10.1.jar` from the source code available on this repo.

**Comment by bcarrier** [comment]
An updated deb is now part of the github release. https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.10.1/sleuthkit-java_4.10.1-1_amd64.deb
