### ISSUE TITLE
memleak may  occur in sleuthkit

### ISSUE THREAD

**Issue by sungguoshuai** [sleuthkit/sleuthkit#2096]
When I test the latest source code with fuzz(which can be found in https://github.com/google/oss-fuzz/tree/master/projects/sleuthkit ),the following stack is display:

==8==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x51dc2d in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x555b59 in tsk_malloc /src/sleuthkit/tsk/base/mymalloc.c:32:16
    #2 0x55b27b in dos_load_ext_table /src/sleuthkit/tsk/vs/dos.c:686:21
    #3 0x559b4e in dos_load_prim_table /src/sleuthkit/tsk/vs/dos.c:1007:17
    #4 0x558db9 in tsk_vs_dos_open /src/sleuthkit/tsk/vs/dos.c:1096:9
    #5 0x5509e0 in tsk_vs_open /src/sleuthkit/tsk/vs/mm_open.c:188:20
    #6 0x550450 in LLVMFuzzerTestOneInput /src/sleuthkit_mmls_fuzzer.cc:38:8
    #7 0x458571 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #8 0x4438d2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:296:6
    #9 0x449967 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:776:9
    #10 0x471fb2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #11 0x7f6d816ea82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 512 byte(s) leaked in 1 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

Could it be a memleak? I am waiting for your response, Thank you~

**Comment by DistantNight** [comment]
/tsk/vs/dos.c line772 dos_load_ext_table()

**Comment by uckelman-sf** [comment]
@simsong This was fixed in PR #2380 and should be closed.
