### ISSUE TITLE
configure.ac unsafe for generic cross-compiling

### ISSUE THREAD

**Issue by brunosmmm** [sleuthkit/sleuthkit#2128]
In here,

https://github.com/sleuthkit/sleuthkit/blob/93ad724fa4995d252851df64292e3d9c4708d16b/configure.ac#L95-L106

Only compilers with the -mingw string are considered as cross-compilers. Compilation will fail for any other architecture due to the generic enforcement of CPPFLAGS and LDFLAGS.

**Comment by uckelman-sf** [comment]
PR #1875 fixes this by removing the whole block, which was never correct to begin with.
