### ISSUE TITLE
Project information on sleuthkit.org out of date

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#2287]
Please update http://www.sleuthkit.org/sleuthkit/desc.php

**Comment by joachimmetz** [comment]
And this likely as well http://www.sleuthkit.org/sleuthkit/licenses.php seeing this project uses several other licenses

**Comment by simsong** [comment]
@joachimmetz — What changes do you want made?  Let me know and I'll email @bcarrier . 

However, this issues isn't for tracking bugs on www.sleuthkit.org. That's a different project. Sorry!

**Comment by joachimmetz** [comment]
So https://www.sleuthkit.org/sleuthkit/licenses.php would need to match the information in https://github.com/sleuthkit/sleuthkit/blob/develop/licenses/README.md

http://www.sleuthkit.org/sleuthkit/desc.php could benefit of having some additional information of all the stuff that has been added to the project since its last update

> However, this issues isn't for tracking bugs on [www.sleuthkit.org](http://www.sleuthkit.org/). That's a different project. Sorry

where is the issue tracker of that? could this be moved to the issue tracker of that project instead?

**Comment by simsong** [comment]
I think that the issue tracker for www.sleuthkit.org <http://www.sleuthkit.org/> is Brian’s inbox.

**Comment by joachimmetz** [comment]
Adding @bcarrier to generate and email

**Comment by bcarrier** [comment]
License page was updated to refer to the new README file in the repo (thanks for that doc) and desc page was updated to reflect image formats and file systems that are now supported.
