### ISSUE TITLE
Inconsistent use of libtsk API by fls (and possibly other tools)?

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#2348]
Docstrings say: `Progs should call tsk_img_close()` (see: https://github.com/sleuthkit/sleuthkit/blob/0239c5934e348699d0be38f694fb6320252a91fc/tsk/img/tsk_img.h#L104) but fls.cpp uses `img->close()` (see: https://github.com/sleuthkit/sleuthkit/blob/0239c5934e348699d0be38f694fb6320252a91fc/tools/fstools/fls.cpp#L390)

Are the docstrings here out of date or are the tools not following the API?

Also https://github.com/sleuthkit/sleuthkit/blob/0239c5934e348699d0be38f694fb6320252a91fc/tools/fstools/fls.cpp#L385 overwrites `img` I'm wondering if that will cause a leak

**Comment by joachimmetz** [comment]
Also `pool->get_img_info` appears to be able to return NULL (see: https://github.com/sleuthkit/sleuthkit/blob/0239c5934e348699d0be38f694fb6320252a91fc/tsk/pool/apfs_pool_compat.cpp#L303) and in the next line it is blindly assumed to be set `img->sector_size` (see: https://github.com/sleuthkit/sleuthkit/blob/0239c5934e348699d0be38f694fb6320252a91fc/tools/fstools/fls.cpp#L386)

**Comment by joachimmetz** [comment]
> overwrites img I'm wondering if that will cause a leak

confirmed this leaks, change to address some of the leaks https://github.com/sleuthkit/sleuthkit/pull/2355

**Comment by bcarrier** [comment]
Yes, the tools should use tsk_img_close() since that also frees a lock. But, the program is going away, so it doesn't really matter.  But, in the name of consistency, yes, we should update the various tools to call tsk_img_close(img) instead of img->close(). 

There are a bunch of others besides the one in 'fls', which was addressed with #2355.

**Comment by joachimmetz** [comment]
> But, the program is going away, so it doesn't really matter.

can you elaborate a bit here about the plans here?

**Comment by bcarrier** [comment]
My comment was only that the tools are all exiting after they call close and the process memory is all getting freed/released.  So, precise cleanup on them is less important than other apps that stay running and open and close many images and file systems. But, consistency is good. 

I did a search and replace and PR #2475 addresses them (img, fs, and pool). 

Thanks.

**Comment by joachimmetz** [comment]
> My comment was only that the tools are all exiting after they call close and the process memory is all getting freed/released.

Thx for the clarification. Note that such leaks make it harder/more time consuming to determine/troubleshoot leaks/memory issues elsewhere.
