### ISSUE TITLE
Inconsistent device block size assigned in hfs.c

### ISSUE THREAD

**Issue by InvisiblePhil** [sleuthkit/sleuthkit#2436]
hfs.c assigns device block size (dev_bsize) as follows:

```
    /* this isn't really accurate; fs->block_size reports only the size
       of the allocation block; the size of the device block has to be
       found from the device (allocation block size should always be
       larger than device block size and an even multiple of the device
       block size) */
    fs->dev_bsize = fs->block_size =
        tsk_getu32(fs->endian, hfs->fs->blk_sz);
```

All other filesystems use the value already stored in TSK_IMG_INFO::sector_size

**Comment by bcarrier** [comment]
@InvisiblePhil I'm trying to find code that actually uses dev_bsize. Did you see an issue with this being teh wrong value? I'm wondering why that value exists any more...

**Comment by InvisiblePhil** [comment]
@bcarrier We've stopped using this variable in all of our code based on your comment, so I suppose the question shifts to whether you would prefer this variable to be deprecated/removed vs having it at least be a 'consistent' value for as long as it is kept.
