### ISSUE TITLE
Implement GitHub Actions or Travis on https://github.com/sleuthkit/sleuthkit

### ISSUE THREAD

**Issue by simsong** [sleuthkit/sleuthkit#2471]
Although this repo has a [.travis.yml](https://github.com/sleuthkit/sleuthkit/blob/develop/.travis.yml) file, it does not appear that Travis is running on pull requests or commits. 

I suggest integrating this repo with Travis directly or else adding support for GitHub Actions. That will make it possible to rapidly validate pull requests.

**Comment by bcarrier** [comment]
Hey Simson.  We disabled it back in May because of the limits that Travis now has for open source projects. It was always timing out and erroring out.  Apparently we can continuously request more credits, but that didn't seem like a long-term solution.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by simsong** [comment]
I've had really good luck with GitHub Actions. Originally @joachimmetz set up Travis for one of my repos, but I moved over to GitHub Actions to keep everything on this site. I found that it's very fast and there's a lot of flexibility. For example, I can configure it so that an action so it runs from cron, or from cron but only when the git commit has been changed, or on every commit, or when a pull request has been updated, and so on. I haven't paid for anything yet since it's an open source project: GitHub's limits seem quite high.

**Comment by joachimmetz** [comment]
This project also has an AppVeyor config, PR pending to extend it with some basics tests https://github.com/sleuthkit/sleuthkit/pull/2428

**Comment by uckelman-sf** [comment]
I've set up GitHub Actions to build and test another project and have been quite happy with it. I'd be willing to contribute a .yml file which will do builds and run tests after my current batch of PRs are merged.

**Comment by uckelman-sf** [comment]
@simsong We're using GitHub Actions now. PR #3008 completes this issue by removing the travis config.
