### ISSUE TITLE
Patches to address integer overflow not included in 4.11.1

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#2622]
@bcarrier looks like https://github.com/sleuthkit/sleuthkit/pull/2566 was not included in 4.11.1 https://github.com/sleuthkit/sleuthkit/blob/release-4.11.1/tsk/fs/iso9660.c#L630

I strongly encourage doing another release that includes all recent patches that fix weaknesses. Now you're exposing users of libtsk to the risks of serious defects.

**Comment by uckelman-sf** [comment]
@simsong This issue was completed by PR #2566 and should be closed.
