### ISSUE TITLE
Error: Transaction test error: file /usr/bin/ils from install of sleuthkit-4.12.0-100.el8.x86_64 conflicts with file from package irods-icommands-4.3.0-1.x86_64

### ISSUE THREAD

**Issue by AGI-chandler** [sleuthkit/sleuthkit#2852]
As you can see, the `ils` binary is conflicting with the binary of the same name from `irods-icommands`, which we also use on our servers.  Is there a suggested workaround?  I'm thinking if there is a way to install either `sleuthkit` or `irods-icommands` as a module, that could work.  We already have some modules available in `/shared/` or `/usr/share/Modules/` for example.  I'll research more about this in the meantime and maybe reach out to Cyverse regarding installing `irods-icommands` as a module also.  Thanks

**Comment by markmckinnon** [comment]
You can compile from source and direct the output to where you want the executables to reside. You should be able to do that with either project.

**Comment by AGI-chandler** [comment]
Yes that could work too, but I got hung up on using the pre-compiled packages and got that working too I think!  By using `dnf --downloadonly install sleuthkit`: `sleuthkit`, `afflib`, `libewf`, `libvhdi`, `libvmdk`, `mac-robber`, and `sleuthkit-libs` RPM's were downloaded to `/var/cache/dnf/${repo}` and then I extracted using `rpm2cpio ${RPM} | cpio -idmv` into `/shared/sleuthkit-4.12.0-100` for example.  Then just copied/edited an existing modulefile to create one for Sleuth Kit and everything seems to work well:
```
$ cat /shared/modulefiles/sleuthkit/4.12.0-100 
#%Module 1.0

proc ModulesHelp { } {
        puts stderr " "
        puts stderr "\tLoads The Sleuth Kit 4.12.0-100, installed"
	puts stderr "\tas a module using RPM's from the forensics repo"
        puts stderr " "
}

module-whatis "Name: sleuthkit"
module-whatis "Version: 4.12.0-100"
module-whatis "Category: Volume and file system data analysis"
module-whatis "Description: The Sleuth Kit (TSK) is a collection of UNIX-based command line tools that allow you to investigate a computer.  The current focus of the tools is the file and volume systems and TSK supports FAT, Ext2/3, NTFS, UFS, and ISO 9660 file systems."

set                     topdir                  /shared/sleuthkit-4.12.0-100

prepend-path            PATH                    $topdir/bin
prepend-path            LD_LIBRARY_PATH         $topdir/lib:$topdir/lib64
prepend-path            LD_RUN_PATH             $topdir/lib:$topdir/lib64
prepend-path            CPATH                   $topdir/include
prepend-path            MANPATH                 $topdir/share/man

$ module avail
-------------------- /shared/modulefiles --------------------
[...]  [...]  [...]  sleuthkit/4.12.0-100  

$ which ils
/usr/bin/ils

$ ils -h
[...]
iRODS Version 4.3.0                ils

$ module load sleuthkit
$ which ils
/shared/sleuthkit-4.12.0-100/bin/ils

$ ils -V
The Sleuth Kit ver 4.12.0
```

Now I realize the filesystem I was interested in is XFS 🤦‍♂️  Oh well at least I learned some things!
