### ISSUE TITLE
Specify --with-libcrypto when you need APFS Decryption!

### ISSUE THREAD

**Issue by aberenguel** [sleuthkit/sleuthkit#2862]
I've seen the file [tsk/tsk_config.h.in](https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/tsk_config.h.in) has not the flag `HAVE_LIBOPENSSL` set. 

So, just running `./boostrap` and `./configure` is not enough to enable SSL.

As the file `tsk/tsk_config.h.in` is versioned, it would be better to add the updated version after run `autoheader`.

```diff
diff --git a/tsk/tsk_config.h.in b/tsk/tsk_config.h.in
index 332929169..5c6f7e0b7 100644
--- a/tsk/tsk_config.h.in
+++ b/tsk/tsk_config.h.in
@@ -65,2 +65,5 @@
 
+/* Define if using openssl */
+#undef HAVE_LIBOPENSSL
+
 /* Define to 1 if you have the `sqlite3' library (-lsqlite3). */
 ```

**Comment by simsong** [comment]
`tsk/tsk_config.h.in should not be part of the git repo. Do you think that this is still an issue?

**Comment by aberenguel** [comment]
Is there another way to enable openssl via config params?

**Comment by simsong** [comment]
What OpenSSL features are you using?

**Comment by aberenguel** [comment]
I'm using APFS decryption.
