### ISSUE TITLE
Broken pkg-config due to unsubstituted variables

### ISSUE THREAD

**Issue by carlsmedstad** [sleuthkit/sleuthkit#2934]
The Arch Linux package for sleuthkit currently ships a broken pkg-config due to the following two variables not being substituted by the build process:

```sh
$ tail -n2 /usr/lib/pkgconfig/tsk.pc
Requires: @AX_PACKAGE_REQUIRES@
Requires.private: @AX_PACKAGE_REQUIRES_PRIVATE@
```

We might be doing something wrong in [our package](https://gitlab.archlinux.org/archlinux/packaging/packages/sleuthkit/-/blob/main/PKGBUILD), but we suspect this to be upstream issue.

Not a pkg-config or automake expert, but I think either the AX_* functionality was broken from the start, or it has been broken since it was introduced in https://github.com/sleuthkit/sleuthkit/pull/1877.

For context, our issue for the Arch Linux package for sleuthkit: https://gitlab.archlinux.org/archlinux/packaging/packages/sleuthkit/-/issues/1.

**Comment by uckelman-sf** [comment]
What in particular makes you think this has been broken since #1877? We've been using that successfully for years. I'll take a look at what you're doing, but I don't hold out much hope of anybody merging a patch if I do find a problem and fix it.

**Comment by uckelman-sf** [comment]
I ought to be getting to this in the coming week.

**Comment by carlsmedstad** [comment]
@uckelman-sf This turned out to be an issue with our package rather than the build process, so no need to look into this. See https://gitlab.archlinux.org/archlinux/packaging/packages/sleuthkit/-/merge_requests/1.

Sorry for not getting back to you earlier, I was waiting for feedback from the maintainer for the package. Closing.

**Comment by uckelman-sf** [comment]
@carlsmedstad Cool, that's for confirming it's ok now.
