### ISSUE TITLE
iPhone image

### ISSUE THREAD

**Issue by vm248** [sleuthkit/sleuthkit#2988]
Hello everyone, 

is it possible to take an image of my iPhone with the Sleuth Kit? Unfortunately, I have forgotten my iPhone PIN and would like to back up my data.

Thank you!

**Comment by simsong** [comment]
Unfortunately, Sleuth Kit does not have an imaging tool.

**Comment by vm248** [comment]
Is it possible for me to read out the memory of my iphone directly without having made a backup beforehand? in other words, can i analyse the memory directly via a usb connection?

**Comment by simsong** [comment]
No.
