### ISSUE TITLE
configure: disable javac if not available

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#3029]
Currently configure fails with `configure: error: no acceptable Java compiler found in $PATH` why is it a requirement to have to pass `--disable-java` ? Can the default behavior of configure be changed to just continue without Java given this is possible with `--disable-java`

**Comment by joachimmetz** [comment]
Also https://github.com/sleuthkit/sleuthkit/blob/develop/configure.ac#L85 says `Add enable/disable option` but configure only provides `--disable-java          Do not build the java bindings or jar file`

**Comment by uckelman-sf** [comment]
Closed by PR #3038.

**Comment by simsong** [comment]
@brianc - I think that the default should be not to build java unless requested, since most TSK users probably do not require the Java bindings. 

As of #3038, you need to do `--enable-java` to enable it. I think that's fine?
