### ISSUE TITLE
Put test images in submodule

### ISSUE THREAD

**Issue by uckelman-sf** [sleuthkit/sleuthkit#3044]
Presently, the test images which are used by the fiwalk tests are fetched using `get_test_images.py`. It would require no code at all if those test images were in a submodule instead, as they'd be checked out at the same time as the main repo (if desired).

@simsong Should we create a subrepo in which to store test images?

**Comment by simsong** [comment]
I've thought about that. What's your thought on the disk space requirements?

**Comment by uckelman-sf** [comment]
The entire repo is about 370MB. The test images which are downloaded to `tests/from_brian` are 35MB. I think there's no problem presently with disk space.

**Comment by simsong** [comment]
Okay. I’ll do it!

**Comment by uckelman-sf** [comment]
I thought that creating a repo for test images would be a 5-minute job. Has something gone wrong?

**Comment by simsong** [comment]
I have had a lot of other things to do. The repo is created, but not populated. I can do that today or tomorrow.

**Comment by simsong** [comment]
i'm not going to get to this tonight. Perhaps tomorrow.

**Comment by simsong** [comment]
https://github.com/sleuthkit/sleuthkit_test_data

**Comment by simsong** [comment]
I have added the images on my local machine, but don't have write access to the repo yet. Either @bcarrier  or @jayaramcs needs to fix this.

**Comment by bcarrier** [comment]
Sorry. Fixed.

**Comment by simsong** [comment]
```
simsong@Simsons-MacBook-Pro sleuthkit_test_data % git push origin
Uploading LFS objects: 100% (10/10), 15 MB | 675 KB/s, done.
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 10 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 2.21 KiB | 2.21 MiB/s, done.
Total 14 (delta 0), reused 0 (delta 0), pack-reused 0
To ssh://github.com/sleuthkit/sleuthkit_test_data
   0bf9304..03d276b  main -> main
simsong@Simsons-MacBook-Pro sleuthkit_test_data %
```
@uckelman-sf will be happy.
