### ISSUE TITLE
rename `master` branch to be `main`

### ISSUE THREAD

**Issue by simsong** [sleuthkit/sleuthkit#3057]
There's been a big renaming of branches throughout GitHub and the git world in general.

Should we do this?

**Comment by simsong** [comment]
Looking for comment from @bcarrier and @jayaramcs before I proceed.

**Comment by uckelman** [comment]
Yes, but we should also _use_ `main`, in that case. `develop` is an odd name for the main branch.

**Comment by simsong** [comment]
My understanding is that we are operating on the develop branch and main is the production branch. Perhaps at some point develop will be renamed main, once we are done with all of the updates and both Brian and Jayaram sign off.

**Comment by bcarrier** [comment]
Circling back on the above comments, we were following the gitflow branching model.  

https://nvie.com/posts/a-successful-git-branching-model/

**Comment by simsong** [comment]
> Circling back on the above comments, we were following the gitflow branching model.
> 
> https://nvie.com/posts/a-successful-git-branching-model/

Thanks!  I thought that was what we were doing, but it's great to have that reference.
