### ISSUE TITLE
can not build on linux

### ISSUE THREAD

**Issue by peterclemenko** [sleuthkit/sleuthkit#320]
Linux, specifically Ubuntu 14.04 64 bit, returns the following output when trying to configure:

/dev/dfir/tsk/sleuthkit$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

**Comment by graytips** [comment]
This is the step i followed to install sleuthkit on ubuntu 14.04 64 bit

reference:http://users.ox.ac.uk/~coml0454/blog/2014/08/25/setting-up-sleuthkit-and-autopsy-on-an-aws-ec2-instance/

sudo apt-get -y install build-essential linux-headers-$(uname -r)
sudo apt-get install zlib1g-dev libssl-dev libncurses5-dev
sudo apt-get install libcurl4-openssl-dev libexpat1-dev libreadline-gplv2-dev
sudo apt-get install uuid-dev libfuse-dev bzip2 libbz2-dev git
sudo apt-get -y install automake1.9  autoconf libtool

Install libewf
wget -v https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/libewf-20140608.tar.gz

tar -xvf libewf-20140608.tar.gz
cd libewf-20140608/
./configure
make
sudo make install

Install AFFLIB
cd~
git clone git://github.com/simsong/AFFLIBv3.git
cd AFFLIBv3/
./bootstrap.sh
./configure
make
sudo make install

Install Sleuthkit
cd ~
git clone git://github.com/sleuthkit/sleuthkit.git
cd sleuthkit
./bootstrap
./configure
make
sudo make install

All the utilities available in sleuthkit is working fine :)

**Comment by kefir-** [comment]
Here's a very similar recipe I use to build libewf, sleuthkit and autopsy on Ubuntu 14.04. I don't use afflib. 

http://forum.sleuthkit.org/viewtopic.php?f=5&t=106

Ps, this issue can be closed, as sleuthkit certainly has built on Linux on the past year since this report.
