### ISSUE TITLE
tsk_loaddb: foreign key constraint failed

### ISSUE THREAD

**Issue by egall** [sleuthkit/sleuthkit#362]
I'm having an issue with tsk_loaddb on a 32 bit machine. Here's the error:
> tsk_loaddb -d ~/scratch/databases/m57.db ~/imagemnt/m57-redacted-charlie-2009-12-10.aff.raw 
Error: Database Error (Error adding data to tsk_file_layout table: foreign key constraint failed
)
Error: Database Error (Error adding data to tsk_file_layout table: foreign key constraint failed
)
Database stored at: ~/scratch/databases/m57.db

Linux xxxxxxxxxxxxx 3.11.4-201.fc19.i686.PAE #1 SMP Thu Oct 10 14:44:46 UTC 2013 i686 i686 i386 GNU/Linux

**Comment by kefir-** [comment]
I had the same issue in #373, I've seen it when I've been running out of memory (the program didn't die though, it ran to completion). Rerunning against the same image with more memory avoided the issue. I haven't verified that everything is correct after seeing errors like this, but it doesn't really sound too promising.

Here's the source where this happens:

https://github.com/sleuthkit/sleuthkit/blob/a0a29d43863aba5b05ce1fa744b26c8fa8d170f2/tsk/auto/db_sqlite.cpp#L964

and the "foreign key constraint failed" seems to indicate that the actual file's obj_id doesn't exist in the tsk_objects table.

**Comment by bcarrier** [comment]
Is that the same image as this:

http://digitalcorpora.org/corpora/scenarios/2009-m57-patents/drives-redacted/charlie-2009-12-10.E01

**Comment by bcarrier** [comment]
I just downloaded this and confirmed it.
