### ISSUE TITLE
How to Install/Compile on Windows Vista 32 with mingw

### ISSUE THREAD

**Issue by ghost** [sleuthkit/sleuthkit#365]
Hello, 

I try to install the project, and I'am following the README_win32.txt.
I have installed mingw32 with tool for development, set the path.

It say use ./configure and make, but unfortunately I don't have configure file.
So I have tried to use bootstrap, but that doesn't work : 

configure.ac:23: warning: macro `AM_PROG_LIBTOOL' not found in library
bootstrap: line 3: libtoolize: command not found
bootstrap: line 3: glibtoolize: command not found

What is the good method ?

Thank you

**Comment by simsong** [comment]
Hi. It looks like you needed to install libtool. 
I'm closing this one.
