### ISSUE TITLE
Multiple infinite loops in HFS+ module

### ISSUE THREAD

**Issue by sburford** [sleuthkit/sleuthkit#407]
The HFS+ module in 4.1.3 has infinite loop, infinite recursion and divide by zero bugs. The patch below shows where they are.

diff --git a/tsk/fs/hfs.c b/tsk/fs/hfs.c
index 805ebff..72a58a6 100644
--- a/tsk/fs/hfs.c
+++ b/tsk/fs/hfs.c
@@ -992,6 +992,15 @@ hfs_cat_traverse(HFS_INFO * hfs, const void *targ_data,
                 is_done = 1;
                 break;
             }
+            // TODO: Handle multinode loops
+            if (next_node == cur_node) {
+                tsk_error_set_errno(TSK_ERR_FS_GENFS);
+                tsk_error_set_errstr
+                    ("hfs_cat_traverse: node %d references itself as next node",
+                    cur_node);
+                is_done = 1;
+                break;
+            }
             cur_node = next_node;
         }
 
@@ -6076,6 +6085,11 @@ hfs_open(TSK_IMG_INFO * img_info, TSK_OFF_T offset,
             tsk_fs_free((TSK_FS_INFO *)hfs);
 
             /* just re-open with the new offset, then record the offset */
+            if (hfsplus_offset == 0) {
+                tsk_error_set_errno(TSK_ERR_FS_CORRUPT);
+                tsk_error_set_errstr("HFS+ offset is zero");
+                return NULL;
+            }
             fs_info2 =
                 hfs_open(img_info, offset + hfsplus_offset, ftype, test);
 
@@ -6109,6 +6123,11 @@ hfs_open(TSK_IMG_INFO * img_info, TSK_OFF_T offset,
         tsk_getu32(fs->endian, hfs->fs->blk_sz);
 
     // determine the last block we have in this image
+    if (fs->block_size <= 1) {
+        tsk_error_set_errno(TSK_ERR_FS_CORRUPT);
+        tsk_error_set_errstr("HFS+ allocation block size too small");
+        return NULL;
+    }
     if ((TSK_DADDR_T) ((img_info->size - offset) / fs->block_size) <
         fs->block_count)
         fs->last_block_act =

**Comment by bcarrier** [comment]
Thanks. Can you submit this as a pull request? Or e-mail me the patch at carrier <at> sleuthkit {dot} org?

**Comment by bcarrier** [comment]
Merged in.   I was able to get a clean patch by "editing" your comment and copying that.  Thanks.
