### ISSUE TITLE
fatxxfs.c missing sanity check

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/sleuthkit#522]
In tsk/fs/fatxxfs.c line 831-833:

    test_dir1 = tsk_fs_dir_open_meta(fs, fs->root_inum);
     
    if(test_dir1->names_used <= 4){ // At most four automatic directores ($MBR, $FAT1, $FAT1, $OrphanFiles)

`tsk_fs_dir_open_meta()` returns NULL on error, but there is no checking of the return value, and `test_dir1->names_used` is referenced immediately. This causes a segfault on some corrupt images.

**Comment by bcarrier** [comment]
Thanks.  This was fixed back in June on the collaborative branch, which has now been merged into develop.
