### ISSUE TITLE
SIGFPE in tsk/fs/ext2fs.c

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/sleuthkit#526]
`tsk/fs/ext2fs.c` can get a SIGFPE because of a divide by zero on malformed input. This happens in this code, starting from line 3353:

            ext2fs->groups_count =
                (EXT2_GRPNUM_T) ((tsk_getu32(fs->endian,
                        ext2fs->fs->s_blocks_count) -
                    ext2fs->first_data_block + tsk_getu32(fs->endian,
                        ext2fs->fs->s_blocks_per_group) -
                    1) / tsk_getu32(fs->endian,
                    ext2fs->fs->s_blocks_per_group));

where `ext2fs->fs->s_blocks_per_group` is zero. Here's a link to a sample image:

https://www.dropbox.com/s/dx48hv9rriv633v/ext2-sigfpe-blocks-per-group.dd?dl=0

I have another similar example, SIGFPE on line 558:

        grp_num = (EXT2_GRPNUM_T) ((dino_inum - fs->first_inum) /
            tsk_getu32(fs->endian, ext2fs->fs->s_inodes_per_group));

It looks like the same can happen several other places.

**Comment by bcarrier** [comment]
Thanks.  This was fixed as part of #543.
