### ISSUE TITLE
sleuthkit crashes on specific image file

### ISSUE THREAD

**Issue by eklann** [sleuthkit/sleuthkit#540]
When running for example the following command:
"fsstat DSIII.E01"
I get a Windows crash dialogue saying that fsstat has stopped working. I suspect that this is a bug in sleuthkit since other .E01 files works fine. 

I have compiled 4.2.0 from source with visual studio under windows 8.1.

I'm happy to give you the .E01 file in question, but since it is 1.3GB in size I wonder how you want me to send it to you?

**Comment by bcarrier** [comment]
@eklann, I know it has been a while since you reported this, but do you still have a copy of the E01 you can share.

**Comment by eklann** [comment]
Hi!

I still have the disk image, and I can share it with you. The image contains some test data from the company I work at, so please don't distribute it further.

How do you want me to transfer the file? Do you have an ftp or something similar where I can upload it?

**Comment by bcarrier** [comment]
Great. Shoot me an email at carrier at sleuthkit dot org and I'll get you a private location.  Thanks!

**Comment by bcarrier** [comment]
Got it, thanks.  It worked fine on my Mac, but crashed on Windows.  We'll take a look at this (along with #393).

**Comment by bcarrier** [comment]
This was fixed with PR #843.
