### ISSUE TITLE
Build failed when installing from git (Ubuntu 14.04)

### ISSUE THREAD

**Issue by i3visio** [sleuthkit/sleuthkit#545]
Hi there,

We've been trying to start a clean installation of sleuthkit in an Ubuntu Trusty (14.04) system. After doing:
```
git clone https://github.com/sleuthkit/sleuthkit
cd sleuthkit
./bootstrap
./configure
make
```
In this process, make process crashes and we receive the following message:
```
...
Making all in jni
make[2]: Entering directory '/opt/autopsy/sleuthkit/bindings/java/jni'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/opt/autopsy/sleuthkit/bindings/java/jni'
make[2]: Entering directory '/opt/autopsy/sleuthkit/bindings/java'
ant dist
Buildfile: /opt/autopsy/sleuthkit/bindings/java/build.xml

BUILD FAILED
Target "copyLibsDebug-PostgreSQL" does not exist in the project "DataModel". It is used from target "Debug-PostgreSQL".

Total time: 0 seconds
Makefile:693: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 1
make[2]: Leaving directory '/opt/autopsy/sleuthkit/bindings/java'
Makefile:421: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/autopsy/sleuthkit/bindings/java'
Makefile:559: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
We're not sure about how  to solve this issue.

**Comment by dkarpo** [comment]
Hello.

Can you confirm if you are still having this issue?  I think it can be closed as it appears to have been addressed at the beginning of [November 2015](https://github.com/sleuthkit/sleuthkit/blob/e90903b61435c334f1cb8ddd598f44eddb2b311e/bindings/java/build.xml)

**Comment by i3visio** [comment]
That's correct. We managed to build now. Closing the issue.

**Comment by afik** [comment]
Hi, can you tell me how you solve this issue? I'm trying to build autopsy and follow steps from autopsy/BUILDING.txt but when running steps 2b. `ant dist-PostgreSQL` in binding/java I get similar error 

`BUILD FAILED
Target "dist-PostgreSQL" does not exist in the project "DataModel".`

**Comment by karlmortensen** [comment]
Are you running the command from the sleuthkit/bindings/java folder?
The other thought is if you have a really old version of the code, the
target name changed from PostgreSQL to dist-PostgreSQL, but that was in
October 2015.

**Comment by slippery60** [comment]
Hi I have the same problem as afik, 

$ ant dist-PostgreSQL

BUILD FAILED
Target "dist-PostgreSQL" does not exist in the project "Datamodel".

I started from my ../sleuthkit-4.2.0/bindings/java sub-directory.

**Comment by karlmortensen** [comment]
Interesting. I don't see that error when I run it.

1) What operating system are you on?
2) What branch of TSK code?
3) What is the latest commit of TSK code for your branch?
4) Did you successfully build TSK in Visual Studio?
5) Probably doesn't matter, but what version of the JDK, and is it 32 or
64-bit?

Sincerely,
  Karl

**Comment by afik** [comment]
Hi @slippery60. It turns out that I followed the wrong instruction. I build on Ubuntu, but I followed steps in https://github.com/sleuthkit/autopsy/blob/develop/BUILDING.txt, which made for Windows . Make sure you doesn't repeat my fault. 
The correct steps for linux installation is [here](https://github.com/sleuthkit/sleuthkit/blob/develop/INSTALL.txt), and if you wanna build autopsy take a look at script [here](https://forum.sleuthkit.org/viewtopic.php?f=5&t=106&start=10#p2981).

**Comment by slippery60** [comment]
karlmortensen;
I was using the incorrect instructions.  They for compiling TSK.    My final goal is to compile Autopsy 4 for linux.   The instructions that generated the error were in the BUILD.txt file in that program. 


Thanks.
