### ISSUE TITLE
Bug in db_sqlite.cpp prevents opening existing cases in Linux

### ISSUE THREAD

**Issue by scott-conrad** [sleuthkit/sleuthkit#561]
The *TskDbSqlite::dbExists()* function does not work properly in Linux.

Line **1069** should be changed from:

>if (TSTAT(m_dbFilePath, &stat_buf) == 0) {
>        // database file exists
>        return true;
>    }

To something like:

>if (m_utf8) {
>    if (TSTAT(m_dbFilePathUtf8, &stat_buf) == 0) {
>        // database file exists
>        return true;
>    }
>}
>else{
>    if (TSTAT(m_dbFilePath, &stat_buf) == 0) {
>        // database file exists
>        return true;
>    }
>}

So that the Linux path is used.
(Sorry, I don't know how to do a pull request.)

**Comment by lfcnassif** [comment]
I am also seeing this problem on develop branch, it prevents adding new images to an existing sqlite produced by tsk_loaddb. The fix seems to be much simple, but TSTAT function does not accept m_dbFilePathUtf8 variable, and I am not a C expert to propose an alternative call.

**Comment by lfcnassif** [comment]
The problem is that it does not compile on Windows, must use
	if (m_utf8) {
		if (stat(m_dbFilePathUtf8, &stat_buf) == 0) {
			// database file exists
			return true;
		}
	}
	else{
		if (TSTAT(m_dbFilePath, &stat_buf) == 0) {
			// database file exists
			return true;
		}
	}

**Comment by bcarrier** [comment]
This should now be fixed. Thanks!
