### ISSUE TITLE
TSK should allow for externally provided images

### ISSUE THREAD

**Issue by sf-jonstewart** [sleuthkit/sleuthkit#562]
Presently working on a patch to address this, so wanted to raise the issue and get some discussion if necessary.

Our patch would add a new API function, `tsk_img_open_external`. The purpose of this function would be to initialize some aspects of a user-supplied `TSK_IMG_INFO`, namely the `tag` and `cache_lock` fields. With this, the user can then set the function pointers in `TSK_IMG_INFO` as appropriate and create their own disk image handling implementations, without further need for modification of libtsk.

`tsk_img_open_external` takes the essential parameters required to initialize the members of `TSK_IMG_INFO`. Alternately, `tsk_img_open_external` could simply take a pointer to the `TSK_IMG_INFO` struct and then rely upon the user to set the members.

In order to ensure proper destruction of `cache_lock`, the patch also removes calls to `tsk_deinit_lock` from the image specific _close functions and promotes them to `tsk_img_close` directly. This ensures the lock is destroyed regardless of open method. We don't see any immediate problems with moving `tsk_deinit_lock` up to `tsk_img_close`. To maintain parallelism, we also promote calls to `tsk_init_lock` up to `tsk_img_open` and `tsk_img_open_external` from the existing image-specific open functions.

Patch to follow shortly. It's not that big of a patch and significantly makes libtsk more flexible.

**Comment by uckelman** [comment]
The patch is in https://github.com/sleuthkit/sleuthkit/pull/565.

**Comment by bcarrier** [comment]
Closing this since the PR was pulled.  Thanks.
