### ISSUE TITLE
Feature request: machine readable alternatives for body files

### ISSUE THREAD

**Issue by noxdafox** [sleuthkit/sleuthkit#623]
I am writing a parser relying on the output of the fls -m command and I'm facing few issues.

The lack of a reliable data structure for the output, makes the tool quite fragile. Specifically crafted file names could break the parser very easily.

An example of a problematic file name could be: "a|b|\n|c"
In this case, the body file would contain a line very difficult to parse. The mactime tool in this case, completely misses the file.

I guess a proper solution for such cases would be adopting a more structured output formats such as JSON or XML. In order not to break backward compatibility, a separate flag such as '-o json/-o xml' could be provided to tools such as fls and ils.

**Comment by noxdafox** [comment]
Another example of problematic file name: "foobar (deleted)"

Is this a deleted file or a file with deleted in its name?

**Comment by ajnelson-nist** [comment]
It sounds like you are hitting some of the early motivations of [Digital Forensics XML](http://forensicswiki.org/wiki/Category:Digital_Forensics_XML).  Is there something that DFXML/`fiwalk`, and/or `tsk_loaddb`, isn't doing that you need?

**Comment by noxdafox** [comment]
This is exactly what I was looking for! Thanks!

I have a question about fiwalk: is there a detailed description about the output format? I looked around and didn't find any. 

Main issue I'm having is how deleted files are reported in the XML as I see many of them having fields <alloc> and <used> set to 1 event though are removed from the image.

**Comment by ajnelson-nist** [comment]
That link you found is out of date.  I'll note that to the the group maintaining that site.

The first link on the wiki article I linked is to the [DFXML schema](https://github.com/dfxml-working-group/dfxml_schema), which describes Fiwalk's output.  Deleted-file status is denoted in the [alloc element](https://github.com/dfxml-working-group/dfxml_schema/blob/master/dfxml.xsd#L63), though that may change in the future (per [this issue](https://github.com/dfxml-working-group/dfxml_schema/issues/14).

**Comment by noxdafox** [comment]
Tried fiwalk on few disk images and it's sensitively slower than tools such as fls. In my use case speed is quite important especially if the difference is one order of magnitude (fls takes 5 seconds were fiwal takes one minute).

Is there a way to get similar speed of fls?

If not, I guess the feature request will still be valid.

Would be enough to have even a simple way to define the output format such as in the command 'stat -c'.
An alternative could be having a '-print0' flag such as for the find command, from the manpage:

> print0: print the full file name on the standard output, followed by a null character (instead of the newline character that -print uses).  This allows file names that contain newlines  or  other
              types of white space to be correctly interpreted by programs that process the find output.

**Comment by ajnelson-nist** [comment]
I haven't done a speed comparison between fls and fiwalk.  If fiwalk's speed is a deal-breaker for you, then you'll probably have to reopen the issue and clarify a little more what your objectives are.

**Comment by ajnelson-nist** [comment]
It sounds to me like you will need custom code after all.  There is the internal C library that Fiwalk and tsk_loaddb use.  There are the Java bindings that the Autopsy project uses.  There are also the Python bindings that somebody else has developed, [pytsk](https://github.com/py4n6/pytsk).  Hopefully one of those references lets you develop what you want in a timely manner.

**Comment by noxdafox** [comment]
Actually the fls and ils commands are just enough. What they lack is the possibility to specify the output format.

The find command has a -printf flag which allows to set the desired output format. The fls tool could produce its body text file in the following way.

`fls -pr --printf="%m|%n|%i|...|%c\n"   image.dd`

While I would probably use something like:

`fls -pr --printf="%i|%d|%n\0"   image.dd`

Where %i stands for inode, %n name, %d deletion boolean etc..

I might try to provide a patch, it shouldn't be a big change on the fls code. I believe it would make it a bit more flexible.

**Comment by noxdafox** [comment]
Pull request #625 is the first step towards the `-print0` extra flag for fls.

**Comment by noxdafox** [comment]
After investigating a bit I discovered the fls is actually sanitising filenames.

https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/fs_name.c#L458
https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/base/tsk_base_i.h#L194

Therefore this issue is not valid.
