### ISSUE TITLE
Use of 'auto' keyword requires C++11 compilation

### ISSUE THREAD

**Issue by uckelman-sf** [sleuthkit/sleuthkit#682]
Since f22fbdaaaa, libtsk fails to compile:

    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../tsk -I../.. -I./../.. -Wall -Wmultichar -Wstrict-null-sentinel -Woverloaded-virtual -Wsign-promo -pthread -I/usr/local/include -g -O2 -MT guid.lo -MD -MP -MF .deps/guid.Tpo -c guid.cpp  -fPIC -DPIC -o .libs/guid.o
    guid.cpp: In constructor 'Guid::Guid(const string&)':
    guid.cpp:127:7: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
           auto byte = hexPairToChar(charOne, charTwo);
           ^
    guid.cpp:127:12: error: 'byte' does not name a type
           auto byte = hexPairToChar(charOne, charTwo);
                ^
    guid.cpp:128:24: error: 'byte' was not declared in this scope
           _bytes.push_back(byte);
                        ^
    Makefile:439: recipe for target 'guid.lo' failed

In order to use `auto` for type deduction, C++ must be compiled under the C++11 standard or later. I.e., what's missing is the flag `-std=c++11`. Alternatively, `byte` could be delcared as an `unsigned char` instead of `auto`, and the compile flags left unchanged. If C++11 compilation is wanted, please let me know and I'd be happy to supply a patch to `configure.ac` for that.

**Comment by rcordovano** [comment]
Moving to C++ 11 is not something we want to do at this time - it may break builds on some systems. The proposed code change to guid.cpp will work for 'Nix builds, but the problem also needs to be solved on lines 181 and 182 for OS-X builds, where the concrete types will be CFUUIDRef and CFUUIDBytes respectively. This will be our initial plan of attack with backing out guid.cpp as the fallback position.

**Comment by rcordovano** [comment]
The changes to make guid.cpp compile without C++ 11 support have been committed to the develop and release-4.3.0 branches. The master branch will be updated in the near future when the release-4.3.0 branch is merged into it.
