### ISSUE TITLE
NTFS parsing doesn't work properly when the disk sector size is > 512

### ISSUE THREAD

**Issue by jtsylve** [sleuthkit/sleuthkit#700]
MFT Update Sequence Entries are currently being applied at the end of every sector instead of at the end of every 512 bytes.  Because of this, NTFS parsing fails for disks with sector sizes that are greater than 512.

The symptoms of this problem are exhibited as an error of `Cannot determine file system type` in `fls` if you don't pass the `-f ntfs` flag and `Error in metadata structure (dinode_lookup: More Update Sequence Entries than MFT size)` if you do.

**Comment by lfcnassif** [comment]
Hi,

I've tried the patch above with a 4k sector ntfs image but I am getting the following error:
Error: Error in metadata structure (Error: Index list offsets are invalid on entry: 5) (Error walking directory in file system at offset 8388608)
Any ideas?

Thanks,
Luis
