### ISSUE TITLE
Rekall integration

### ISSUE THREAD

**Issue by veyesecurity** [sleuthkit/sleuthkit#702]
We would like to integrate TSK with Rekall memory forensic framework to enable parsing of various filesystems (today only NTFS supported).
Rekall distributed under GPL license and according to CPL FAQ we need your permission for such integration.
We believe that the integration can be very beneficial for both projects.

**Comment by simsong** [comment]
Hi @veyesecurity — I'm closing this because it's kind of old. If you are still interested, please contact us.
