### ISSUE TITLE
Patch to fix spelling errors

### ISSUE THREAD

**Issue by eribertomota** [sleuthkit/sleuthkit#740]
Hi,

The attached patch will fix some spelling errors in final binaries.

Regards,

Eriberto

[fix-spellings.txt](https://github.com/sleuthkit/sleuthkit/files/622205/fix-spellings.txt)

**Comment by eribertomota** [comment]
Sending the file. The zip file was dropped.

[fix-spellings.txt](https://github.com/sleuthkit/sleuthkit/files/622195/fix-spellings.txt)

**Comment by uckelman-sf** [comment]
@simsong This is complete now and should be closed.
