### ISSUE TITLE
Make and keep C code in libtsk C89 compatible

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#882]
Python 2.7 on Windows depends on VS2008 see: https://wiki.python.org/moin/WindowsCompilers

This version of VS requires C code to be C89 compatible, please add a test to check if C code is C89 compatible and fix libtsk where needed

**Comment by bcarrier** [comment]
Looks like your specific failure is from #831.  

Are you proposing that we supply -std=c89 to gcc to ensure that everything is C89?  Is it just that one line in fs_open that is the issue?

**Comment by joachimmetz** [comment]
> Is it just that one line in fs_open that is the issue?

There are only a few lines that cause issues. While getting pytsk to build I found issues in:
* sleuthkit/tsk/fs/fs_name.c
* sleuthkit/tsk/fs/fs_open.c
* sleuthkit/tsk/img/raw.c

Also see: https://github.com/py4n6/pytsk/blob/master/setup.py#L263

> Are you proposing that we supply -std=c89 to gcc to ensure that everything is C89? 

You could use this for testing, though VC 9 for Python on Windows is more strict about C89

**Comment by bcarrier** [comment]
I spent a few minutes on this tonight and added this to configure.ac:

`+CFLAGS="$CFLAGS -std=c89"`

It did not generate any errors for the files mentioned, so this won't help ensure that travis fails if we check in non-compliant code...

**Comment by joachimmetz** [comment]
maybe add appveyor CI testing e.g. https://ci.appveyor.com/project/joachimmetz/libvhdi you see that one of the build targets is VS2008. As indicated that is the most strict one.

Also see AppVeyor config: https://github.com/libyal/libvhdi/blob/master/appveyor.yml
