### ISSUE TITLE
Missing symbols in 4.4.2

### ISSUE THREAD

**Issue by hillu** [sleuthkit/sleuthkit#889]
Hi,

when building The Sleuth Kit 4.4.2 for upload to Debian, I noticed that two symbols that had been there in 4.4.0 are missing:

- `tsk_img_get_names@Base`
- `_ZN9TskAutoDb15addImageDetailsEPKPKciS1_@Base` (the mangled form of `TskAutoDb::addImageDetails(char const* const*, int, char const*)`)

Programs linked against libtsk from version 4.4.0 may no longer work with 4.4.2 which means that the `--version-info` string in `tsk/Makefile.am` should be changed -- I think to 16:1:0.

**Comment by bcarrier** [comment]
Hi hillu.  Thanks for noticing these changes, but we do not consider them public API changes that would impact the version as you indicated.

- tsk_image_get_names() is defined in tsk_img_i.h and we consider the *_i.h files to be for use within the program and not part of the public API.  This method was not available to developers who followed our guidelines about what .h files to include (which would have been tsk_img.h).  
- TskAutoDb::addImageDetails() is a private method, so it would also not effect the public API. Other programers would not have been able to access this method.

**Comment by hillu** [comment]
@bcarrier Have you considered hiding all symbols and only marking those for export that are part of the public API? For GCC this should be possible with `-fvisibility=hidden` and `__attribute__((visibility("default")))`.
