### ISSUE TITLE
fls segfaults in hfs_UTF16toUTF8.

### ISSUE THREAD

**Issue by adambuchbinder** [sleuthkit/sleuthkit#909]
To reproduce:

    $ unzip segfault.zip
    Archive:  segfault.zip
      inflating: segfault.img
    $ fls segfault.img
    Segmentation fault

This bug was found using [american fuzzy lop](http://lcamtuf.coredump.cx/afl/) and input files ultimately from [files.fuzzing-project.org](https://files.fuzzing-project.org/filesystems/).

Backtrace:

```
#0  __memcpy_sse2_unaligned ()
    at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:36
#1  0x0000000000469c44 in memcpy (__len=131070, __src=0x7d0f2e, 
    __dest=0x7ffff7f6e010) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
#2  hfs_UTF16toUTF8 (fs=fs@entry=0x7cecd0, 
    uni=uni@entry=0x7d0f2e '0' <repeats 200 times>..., ulen=65535, 
    asc=asc@entry=0x7fffffffd450 "1+", alen=alen@entry=382, 
    flags=flags@entry=0) at hfs_dent.c:115
#3  0x0000000000455ecb in hfs_load_extended_attrs (
    fs_file=fs_file@entry=0x7cec50, 
    isCompressed=isCompressed@entry=0x7fffffffd650 "", 
    compDataInRSRC=compDataInRSRC@entry=0x7fffffffd660 "", 
    uncompressedSize=uncompressedSize@entry=0x7fffffffd670) at hfs.c:3822
#4  0x0000000000463e3b in hfs_make_catalog (fs_file=0x7cec50, hfs=0x7cecd0)
    at hfs.c:1940
#5  hfs_inode_lookup (fs=0x7cecd0, a_fs_file=0x7cec50, inum=<optimized out>)
    at hfs.c:2573
#6  0x0000000000428821 in tsk_fs_file_open_meta (a_fs=a_fs@entry=0x7cecd0, 
    a_fs_file=a_fs_file@entry=0x0, a_addr=a_addr@entry=4) at fs_file.c:128
#7  0x00000000004410fb in hfs_open (img_info=<optimized out>, 
    offset=<optimized out>, ftype=<optimized out>, test=<optimized out>)
    at hfs.c:6299
#8  0x0000000000435998 in tsk_fs_open_img (a_img_info=0x7ffff7f8f010, 
    a_offset=0, a_ftype=<optimized out>) at fs_open.c:124
#9  0x0000000000409b94 in main (argc=<optimized out>, argv1=<optimized out>)
    at fls.cpp:267
```

Input: [segfault.zip](https://github.com/sleuthkit/sleuthkit/files/1252241/segfault.zip)

**Comment by jtsylve** [comment]
This can happen when `hfs_btree_key_attr::attr_name_len` is set to a number that's larger than the size of `hfs_btree_key_attr::attr_name`.

A sanity check is needed before this call.

https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/hfs.c#L3822

**Comment by jtsylve** [comment]
Actually my last statement isn't entirely correct. The allocation isn't of the structure itself, but is based on a node size (which is read from an image and thus is user controllable), which could mean that the entire structure we're reading from can be truncated.

**Comment by bcarrier** [comment]
This image doesn't cause a segfault for me on either OS X or Windows.  But, I did add a bunch more bounds checks to that method (including for the name).
