### ISSUE TITLE
Consider moving unittests under tests and define tests in tests/Makefile.am

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#923]
To have a single "Testsuite summary" consider moving unittests under tests and define tests in tests/Makefile.am

Also see:
https://travis-ci.org/sleuthkit/sleuthkit/jobs/268859917#L1959
https://travis-ci.org/sleuthkit/sleuthkit/jobs/268859917#L2005

Also consider using public test images or add a repo sleuthkit/testimages for the tests to download the testimages.

**Comment by uckelman-sf** [comment]
I'm doing this presently.

**Comment by uckelman-sf** [comment]
See PR #3059.

**Comment by uckelman-sf** [comment]
See PR #3063.
