### ISSUE TITLE
Error while running fls command

### ISSUE THREAD

**Issue by AndreasProof** [sleuthkit/sleuthkit#950]
I am trying to run fls command ( oddly a few weeks ago worked) and it doesn't work any more. Bellow is the output of it:

Error reading image file (ewf_image_read - offset: 13405331456 - len: 65536 - No such file or directory) (tsk_fs_file_walk: Error reading block at 3272786  - ntfs_dir_open_meta)

Any suggestions ?

**Comment by bcarrier** [comment]
Are you missing one of the E0x files?

**Comment by AndreasProof** [comment]
Ohhh...damn...thank you!! There was a E0 file missing. Now it's working
