### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [sleuthkit/sleuthkit#974]
Hello SleuthKit,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by bcarrier** [comment]
Hello.  Please submit any security issues to secure <at> sleuthkit.org and I will work them into our private/internal tracker.

**Comment by Google-Autofuzz** [comment]
Great, thank you!
