### ISSUE TITLE
Problem in compiling sigfind.cpp

### ISSUE THREAD

**Issue by Lazza** [sleuthkit/sleuthkit#988]
I am trying to compile TSK in a Docker container, based on Alpine Linux. Here are the relevant commands:

```
./bootstrap
./configure --prefix=$workingdir/tsk --with-libewf=$workingdir/tsk
make
make install
```

These errors are produced:

```
sigfind.cpp: In function 'int main(int, char**)':
sigfind.cpp:53:5: error: 'daddr_t' was not declared in this scope
     daddr_t i, prev_hit;
     ^
sigfind.cpp:176:14: error: 'i' was not declared in this scope
         for (i = 0; i < 9; i++) {
              ^
sigfind.cpp:282:10: error: 'i' was not declared in this scope
     for (i = 0; i < sig_size; i++) {
          ^
sigfind.cpp:294:5: error: 'prev_hit' was not declared in this scope
     prev_hit = -1;
     ^
```

I am using the `sleuthkit-4.5.0.tar.gz` release and `configure` ran flawlessly. Am I doing something wrong?

**Comment by bcarrier** [comment]
Hmm, it means that it did not know about the 'daddr_t' type, which is often defined in standard header files. Not sure this is the first time we ever see this, but I'm not sure why that type is used in the first place.   It's not used anywhere else.  I removed it.

**Comment by Lazza** [comment]
Thank you. As a side note, I encountered this error while working on a Docker container to run Autopsy on any Linux distro easily (Docker can be used for GUI apps as well, if configured correctly).

Do you think this could be of interest for other users as well?
