### ISSUE TITLE
fiwalk 4.5.0 recording name_type 'V' for  $OrphanFiles fileobject

### ISSUE THREAD

**Issue by timothyryanwalsh** [sleuthkit/sleuthkit#998]
Hi all,

I have [a program](https://github.com/timothyryanwalsh/cca-diskimageprocessor) that automates a large part of the workflow of processing disk images of legacy storage media (floppies, zip disks, and the like) at my museum. It relies pretty heavily on TSK, including fiwalk and tsk_recover, as well as the [DFXML Python bindings](https://github.com/simsong/dfxml), now maintained by @ajnelson.

As of TSK 4.5.0, tests started failing because the Objects.py script from the DFXML Python bindings was finding a name_type of "V" rather than "v" in a fiwalk-created DFXML file. The fileobject with the "V" name_type is an $OrphanFiles directory from a FAT12-formatted 3.5" floppy.

You can see the fiwalk output from the tests [here](https://travis-ci.org/timothyryanwalsh/cca-diskimageprocessor/builds/293257025).

I was able to add in some exception handling but without a DFXML file that Objects.py recognizes as valid, a lot of the functionality fails.

Is a "V" name_type intended or have I found a bug? Thanks!

**Comment by bcarrier** [comment]
This is a new "feature" in 4.5.0.  We are now better identifying Virtual Directories, which are ones that TSK created for data organization purposes.  The lower case 'v' is being used by virtual files and 'V' is for Virtual directories.

**Comment by timothyryanwalsh** [comment]
Ah, okay. That makes sense. Thanks for the quick response!

**Comment by ajnelson-nist** [comment]
Hi Tim,

It looks like this bug can be closed out.  Unless I'm missing another outstanding issue?

--Alex

**Comment by timothyryanwalsh** [comment]
Thanks @ajnelson-nist, and agreed!
